version: "3"

services:
  app:
    image: clientname:latest
    container_name: clientname-magento
    volumes:
      - ./:/var/www/magento2
      - ./docker/volumes/php-fpm:/sock

  nginx:
    image: clientname-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/magento2
      - ./docker/volumes/php-fpm:/sock

  db:
    image: mariadb:10.4
    container_name: mariadb-magento
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volumes/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=clientname

  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
